contact_links:
- name: File a bug report
  url: https://issues.redhat.com/secure/CreateIssueDetails!init.jspa?pid=12332330&issuetype=1&components=12367613&priority=10300&customfield_12316142=26752
  about: Please use the Red Hat Issue Tracker to report bugs.
- name: DNS Operator in OpenShift Container Platform
  url: https://docs.openshift.com/container-platform/latest/networking/dns-operator.html
  about: Refer to the OpenShift Container Platform documentation for information about the DNS Operator in OpenShift Container Platform.
- name: DNS Operator in OKD
  url: https://docs.okd.io/latest/networking/dns-operator.html
  about: Refer to the OKD documentation for information about the DNS Operator in OKD.
